[package]
name = "nats-experiment"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.42.0"
futures = "0.3"
thiserror = "2.0.12"
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
